app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from app.models import User


class CreateLabForm(FlaskForm):
    lab_difficulty = SelectField('Lab Difficulty', choices=['Easy', 'Moderate', 'Expert'], default='Easy',
                                 validators=[DataRequired()])
    submit = SubmitField('Start Lab')


class SubmitLabForm(FlaskForm):
    lab_token = StringField("Lab Token", validators=[DataRequired()])
    submit = SubmitField("Submit Token")

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, url_for, flash, request, session, current_app
from app import db
from flask_login import current_user, login_required
from app.main.forms import CreateLabForm, SubmitLabForm
from app.main import bp
from app.main.handlers import BuildNetwork, DestroyNetwork
import docker
from app.models import ActiveLabs, DockerFiles


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    form = CreateLabForm()
    return render_template('main/index.html', title='Home', form=form)


@bp.route('/start_lab', methods=['POST'])
@login_required
def start_lab():
    difficulty = request.form.get('lab_difficulty')
    new_lab = BuildNetwork(difficulty)
    lab_id = new_lab.run()
    lab = ActiveLabs.query.filter_by(id=lab_id).first()
    return render_template('main/started_lab.html', title='Lab Started', start_ip=lab.entrypoint_ip,
                           lab_token_type=lab.lab_token_type, lab_id=lab_id)


@bp.route('/submit_lab/<lab_id>', methods=['GET', 'POST'])
@login_required
def submit_lab(lab_id):
    form = SubmitLabForm()
    lab = ActiveLabs.query.filter_by(id=lab_id).first()
    if not lab:
        flash("Lab does not exist")
    if form.validate_on_submit():
        if form.lab_token.data == lab.lab_token:
            completed_lab = DestroyNetwork(lab_id)
            if completed_lab.destroy():
                return render_template('main/submit_lab.html', title='Submit Lab', lab_id=lab_id)
            else:
                flash("An error occurred submitting the lab. Please try again.")
                return render_template('main/submit_lab.html', title='Submit Lab', form=form,
                                       lab_token_type=lab.lab_token_type,
                                       lab_id=lab_id)
        else:
            flash("Invalid Token. Please try again.")
            return render_template('main/submit_lab.html', title='Submit Lab', form=form,
                                   lab_token_type=lab.lab_token_type,
                                   lab_id=lab_id)
    return render_template('main/submit_lab.html', title='Submit Lab', form=form, lab_token_type=lab.lab_token_type,
                           lab_id=lab_id)


@bp.route('/profile', methods=['GET'])
@login_required
def profile():
    active_labs = ActiveLabs.query.filter_by(user_id=current_user.get_id(), running=True).all()
    completed_labs = ActiveLabs.query.filter_by(user_id=current_user.get_id(), running=False).all()
    return render_template('main/profile.html', title='Profile', active_labs=active_labs, completed_labs=completed_labs)


@bp.route('/lab_profile/<lab_id>', methods=['GET'])
@login_required
def lab_profile(lab_id):
    lab = ActiveLabs.query.filter_by(id=lab_id).first()
    entry_container = DockerFiles.query.filter_by(id=lab.entrypoint_id).first()
    exit_container = DockerFiles.query.filter_by(id=lab.exit_node_id).first()
    return render_template('main/lab_profile.html', title='Lab Profile', start_ip=lab.entrypoint_ip,
                           lab_token_type=lab.lab_token_type, lab_id=lab_id, entry_container_name=entry_container.name,
                           exit_container_name=exit_container.name, lab_difficulty=lab.difficulty, running=lab.running,
                           lab_token=lab.lab_token)

app/templates/main/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<form action="{{ url_for('main.start_lab') }}" method="post" id="start_lab_form">
    <div class="hidden">
        {{ form.csrf_token }}
    </div>
    {{ wtf.form_field(form.lab_difficulty) }}

    {{ wtf.form_field(form.submit) }}
</form>
{% endblock %}

app/templates/main/lab_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Lab Profile</h1>
<p id="lab_ip">The IP address you should start with is {{ start_ip }}</p>
<p id="lab_token_desc">The lab token you are looking for is {{ lab_token_type }}</p>
<p id="entry_container_name">The entrypoint container name is {{ entry_container_name }}</p>
<p id="exit_container_name">The exit node container name is {{ exit_container_name }}</p>
<p id="difficulty">The difficulty of this lab is {{ lab_difficulty }}</p>
{% if running == true %}
    <p id="is_running">Your lab is currently still running</p>
    <p id="submit_lab">Once you have completed the lab and found your token please click the button below to submit the token</p>
    <a href="{{ url_for('main.submit_lab', lab_id=lab_id) }}"><button type="button" class="btn btn-success btn-lg">Submit Lab</button></a>
{% else %}
    <p id="not_running">You have successfully completed this lab by submitting the lab token</p>
    <p id="lab_token">The lab token you submitted was {{ lab_token }}</p>
{% endif %}

{% endblock %}

app/templates/main/profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>{{ current_user.get_users_name() }}'s Profile</h1>
<div id="active_labs">
    <h3 class="text-center">Active Labs</h3>
    <table class="table" id="active_labs_table">
        <thead>
        <tr>
            <th id="lab_id">Lab ID</th>
            <th id="lab_desc">Lab Token Description</th>
            <th id="date_started">Date Started</th>
        </tr>
        </thead>
        {% for active_lab in active_labs %}
        <tr>
            <td><a href="{{ url_for('main.lab_profile', lab_id=active_lab['id']) }}">{{ active_lab['id'] }}</a></td>
            <td>{{ active_lab['lab_token_type'] }}</td>
            <td>{{ active_lab['date_started'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div id="completed_labs">
    <h3 class="text-center">Completed Labs</h3>
    <table class="table" id="completed_labs_table">
        <thead>
        <tr>
            <th id="completed_labs_lab_id">Lab ID</th>
            <th id="completed_labs_lab_desc">Lab Token Description</th>
            <th id="completed_labs_date_started">Date Started</th>
            <th id="completed_labs_date_completed">Date Completed</th>
        </tr>
        </thead>
        {% for completed_lab in completed_labs %}
        <tr>
            <td><a href="{{ url_for('main.lab_profile', lab_id=completed_lab['id']) }}">{{ completed_lab['id'] }}</a></td>
            <td>{{ completed_lab['lab_token_type'] }}</td>
            <td>{{ completed_lab['date_started'] }}</td>
            <td>{{ completed_lab['date_completed'] }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/main/started_lab.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Your lab has been created successfully</h1>
<p id="lab_started_welcome">The lab has been created and now you can start hacking away on the server.</p>
<p id="lab_ip">The IP address you should start with is {{ start_ip }}</p>
<p id="lab_token">The lab token you are looking for is {{ lab_token_type }}</p>
<p id="submit_lab">Once you have completed the lab and found your token please click the button below to submit the token</p>
<a href="{{ url_for('main.submit_lab', lab_id=lab_id) }}"><button type="button" class="btn btn-success btn-lg">Submit Lab</button></a>
{% endblock %}

app/templates/main/submit_lab.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
{% if form %}
    <h1>Submit Lab Token</h1>
    <h3>Please submit the {{ lab_token_type }} below</h3>
    <form action="{{ url_for('main.submit_lab', lab_id=lab_id) }}" method="post" id="submit_lab_form">
        <div class="hidden">
            {{ form.csrf_token }}
            <input type="text" name="lab_id" value="{{ lab_id }}">
        </div>
        {{ wtf.form_field(form.lab_token) }}

        {{ wtf.form_field(form.submit) }}

    </form>
{% else %}
    <h1>Thanks for submitting the token</h1>
{% endif %}
{% endblock %}